### ISSUE TITLE
Error loading sys-uptime on windows

### ISSUE THREAD

**Issue by jkburges** [djberg96/sys-uptime#3]
I'm getting the following error:

```
irb(main):001:0> require 'sys/uptime'
FFI::NotFoundError: Function 'sysconf' not found in [msvcrt.dll]
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:261:in `attach_function'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sys-uptime-0.7.0/lib/unix/sys/uptime.rb:28:in `<class:Uptime>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sys-uptime-0.7.0/lib/unix/sys/uptime.rb:8:in `<module:Sys>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sys-uptime-0.7.0/lib/unix/sys/uptime.rb:4:in `<top (required)>'
        from (irb):1:in `require'
        from (irb):1
        from C:/Ruby22-x64/bin/irb:11:in `<main>'
```

with

```
PS C:\vagrant> ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
```

**Comment by jkburges** [comment]
Seems like a similar error to https://github.com/djberg96/sys-uname/issues/2

**Comment by jkburges** [comment]
FWIW it's worth, I was able to workaround this with `require 'windows/sys/uptime'`

**Comment by djberg96** [comment]
Try "require 'sys-uptime'".

I guess I should make it so that either one works. Thanks for the report.

**Comment by jkburges** [comment]
Thanks, that works!
